//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lmp.ProductShow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public long id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> age { get; set; }
        public string nickname { get; set; }
    }
}
